In [2]:
import numpy as np
import pandas as pd

In [3]:
url = 'C:/Users/HP/OneDrive/Desktop/GUVI-DS PROJECT REPORTS/OLA_DataSet.xlsx'
df = pd.read_excel(url)

In [4]:
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...

In [5]:
df.info()          # Checking all the information related to the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 20 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        103024 non-null  datetime64[ns]
 1   Time                        103024 non-null  object
 2   Booking_ID                  103024 non-null  object
 3   Booking_Status              103024 non-null  object
 4   Customer_ID                 103024 non-null  object
 5   Vehicle_Type                103024 non-null  object
 6   Pickup_Location             103024 non-null  object
 7   Drop_Location               103024 non-null  object
 8   V_TAT                       63967 non-null   float64
 9   C_TAT                       63967 non-null   float64
 10  Canceled_Rides_by_Customer  10499 non-null   object
 11  Canceled_Rides_by_Driver    18434 non-null   object
 12  Incomplete_Rides            63967 non-null   object
 13  Incomplete_Rides_Reason     3926 non-null    object
 14  Booking_Value               103024 non-null  int64
 15  Payment_Method              63967 non-null   object
 16  Ride_Distance               103024 non-null  int64
 17  Driver_Ratings              63967 non-null   float64
 18  Customer_Rating             63967 non-null   float64
 19  Vehicle Images              103024 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(2), object(13)
memory usage: 15.7+ MB

In [6]:
100*df.isnull().sum()/df.shape[0]        # Checking null percentage for each column

Date                           0.000000
Time                           0.000000
Booking_ID                     0.000000
Booking_Status                 0.000000
Customer_ID                    0.000000
Vehicle_Type                   0.000000
Pickup_Location                0.000000
Drop_Location                  0.000000
V_TAT                         37.910584
C_TAT                         37.910584
Canceled_Rides_by_Customer    89.809171
Canceled_Rides_by_Driver      82.107082
Incomplete_Rides              37.910584
Incomplete_Rides_Reason       96.189237
Booking_Value                  0.000000
Payment_Method                37.910584
Ride_Distance                  0.000000
Driver_Ratings                37.910584
Customer_Rating               37.910584
Vehicle Images                 0.000000
dtype: float64

Handling missing values

Here null values in all the columns are 'Missing at random', so imputing the values acordingly

In [7]:
df['V_TAT'] = df['V_TAT'].fillna(-1)

In [8]:
df['C_TAT'] = df['C_TAT'].fillna(-1)

In [9]:
df['Canceled_Rides_by_Customer'] = df['Canceled_Rides_by_Customer'].fillna('Completed/Driver Canceled')

In [10]:
df['Canceled_Rides_by_Driver'] = df['Canceled_Rides_by_Driver'].fillna('Completed/Customer Canceled')

In [11]:
df['Incomplete_Rides'] = df['Incomplete_Rides'].fillna('Ride not started')

In [12]:
df['Incomplete_Rides_Reason'] = np.where(df['Incomplete_Rides'] == 'No', 'Not an Incomplete Ride', df['Incomplete_Rides_Reason'])
df['Incomplete_Rides_Reason'] = np.where(df['Incomplete_Rides'] == 'Ride not started', 'Ride not started', df['Incomplete_Rides_Reason'])

In [13]:
df['Payment_Method'] = df['Payment_Method'].fillna("Not Applicable")

In [14]:
df['Driver_Ratings'] = df['Driver_Ratings'].fillna(-1)

In [15]:
df['Customer_Rating'] = df['Customer_Rating'].fillna(-1)

In [16]:
100*df.isnull().sum()/df.shape[0]    # Checking the null value percentage again

Date                          0.0
Time                          0.0
Booking_ID                    0.0
Booking_Status                0.0
Customer_ID                   0.0
Vehicle_Type                  0.0
Pickup_Location               0.0
Drop_Location                 0.0
V_TAT                         0.0
C_TAT                         0.0
Canceled_Rides_by_Customer    0.0
Canceled_Rides_by_Driver      0.0
Incomplete_Rides              0.0
Incomplete_Rides_Reason       0.0
Booking_Value                 0.0
Payment_Method                0.0
Ride_Distance                 0.0
Driver_Ratings                0.0
Customer_Rating               0.0
Vehicle Images                0.0
dtype: float64

Checking for data types and changing them if applicable

In [17]:
df.dtypes

Date                          datetime64[ns]
Time                                  object
Booking_ID                            object
Booking_Status                        object
Customer_ID                           object
Vehicle_Type                          object
Pickup_Location                       object
Drop_Location                         object
V_TAT                                float64
C_TAT                                float64
Canceled_Rides_by_Customer            object
Canceled_Rides_by_Driver              object
Incomplete_Rides                      object
Incomplete_Rides_Reason               object
Booking_Value                          int64
Payment_Method                        object
Ride_Distance                          int64
Driver_Ratings                       float64
Customer_Rating                      float64
Vehicle Images                        object
dtype: object

All data types are correct

Removing time from date column(as we already have it seperately)

In [18]:
df['Date'] = df['Date'].dt.date
df['Date'] = pd.to_datetime(df['Date'])

In [19]:
df.dtypes

Date                          datetime64[ns]
Time                                  object
Booking_ID                            object
Booking_Status                        object
Customer_ID                           object
Vehicle_Type                          object
Pickup_Location                       object
Drop_Location                         object
V_TAT                                float64
C_TAT                                float64
Canceled_Rides_by_Customer            object
Canceled_Rides_by_Driver              object
Incomplete_Rides                      object
Incomplete_Rides_Reason               object
Booking_Value                          int64
Payment_Method                        object
Ride_Distance                          int64
Driver_Ratings                       float64
Customer_Rating                      float64
Vehicle Images                        object
dtype: object

In [20]:
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,-1.0,-1.0,Completed/Driver Canceled,Personal & Car related issue,Ride not started,Ride not started,444,Not Applicable,0,-1.0,-1.0,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,Completed/Driver Canceled,Completed/Customer Canceled,No,Not an Incomplete Ride,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,Completed/Driver Canceled,Completed/Customer Canceled,No,Not an Incomplete Ride,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,-1.0,-1.0,Driver is not moving towards pickup location,Completed/Customer Canceled,Ride not started,Ride not started,384,Not Applicable,0,-1.0,-1.0,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,Completed/Driver Canceled,Completed/Customer Canceled,No,Not an Incomplete Ride,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...

Checked the values in each column 
Everything is fine, now the data is ready to load

In [22]:
df.to_csv('ola_Cleaned_Data.csv', index=False)  # Converting the pandas dataframe to csv file